### PR TITLE
Lm messages

### PR DESCRIPTION
**Pull request by Iandonmorgan**
1. git fetch --all
2. git checkout lm-messages
3. note the default value for loggedInUserId = 5 (Landon), to change this, just update the line 5 of code on both messagesEventListeners.js & domManagerMessages.js. // example: const loggedInUserId = 2;
4. play around with the chat section and let me know your thoughts
5. I know of one issue, when editing a previously edited entry, I get a null value returned for a listener; I'll need to work on this before merging to master, but I think I'm close....

### CODE REVIEW

**Review by ChaseSully222 — APPROVED** [review]
This is great! I was able to test all users and save, edit, delete. I also tested the double edit error you mentioned. I think its good to merge now if you want to work on something else and revisit this if we have any extra time. Or, if you think you're close then finish it up and merge. Either way this is awesome and not sure I could've done it myself.

**Comment by mister-michael** [comment]
Works great. Looking forward to the solve for the null, i had an intuition and quadrupled the errors. Go ahead and merge it.

**Review by mister-michael — APPROVED** [review]

**Comment by Iandonmorgan** [comment]
@mister-michael did you check your code? Want to make sure I didn’t change anything for you in data, main, or index. I’ll probably wait to merge until after our standup tomorrow.

**Comment by Iandonmorgan** [comment]
Closing pull request to work on some bugs, will resend pull request for a new version to test, soon.

**Pull request closed without merging**
