### PR TITLE
More buttons

### PR DESCRIPTION
**Pull request by mister-michael**
deleted commented code on main.js
built basic functionality into /scripts/events
if haven't already test API functionality

### CODE REVIEW

**Comment by ChaseSully222** [comment]
Looks good, only suggestions is to add something to cancel out of the edit function, and make sure we are working off a user ID that is logged in.

**Review by Iandonmorgan — CHANGES_REQUESTED** [review]
delete line 16 from main.js

**Review by Iandonmorgan — APPROVED** [review]
👍

**Review by ChaseSully222 — COMMENTED** [review]
👍

**Review by ChaseSully222 — APPROVED** [review]

**Pull request merged**
